class EnvironmentSettings:
    def __init__(self):
        self.workspace_dir = '/mnt/sdc/V4R/WYH/Pytracking/github_ICRA26'    # Base directory for saving network checkpoints.
        self.tensorboard_dir = '/mnt/sdc/V4R/WYH/Pytracking/github_ICRA26/tensorboard'    # Directory for tensorboard files.
        self.pretrained_networks = '/mnt/sdc/V4R/WYH/Pytracking/github_ICRA26/pretrained_networks'
        self.lasot_dir = '/mnt/sdc/V4R/WYH/Pytracking/github_ICRA26/data/lasot'
        self.got10k_dir = '/mnt/sdc/V4R/WYH/Pytracking/github_ICRA26/data/got10k/train'
        self.got10k_val_dir = '/mnt/sdc/V4R/WYH/Pytracking/github_ICRA26/data/got10k/val'
        self.lasot_lmdb_dir = '/mnt/sdc/V4R/WYH/Pytracking/github_ICRA26/data/lasot_lmdb'
        self.got10k_lmdb_dir = '/mnt/sdc/V4R/WYH/Pytracking/github_ICRA26/data/got10k_lmdb'
        self.trackingnet_dir = '/mnt/sdc/V4R/WYH/Pytracking/github_ICRA26/data/trackingnet'
        self.trackingnet_lmdb_dir = '/mnt/sdc/V4R/WYH/Pytracking/github_ICRA26/data/trackingnet_lmdb'
        self.coco_dir = '/mnt/sdc/V4R/WYH/Pytracking/github_ICRA26/data/coco'
        self.coco_lmdb_dir = '/mnt/sdc/V4R/WYH/Pytracking/github_ICRA26/data/coco_lmdb'
        self.lvis_dir = ''
        self.sbd_dir = ''
        self.imagenet_dir = '/mnt/sdc/V4R/WYH/Pytracking/github_ICRA26/data/vid'
        self.imagenet_lmdb_dir = '/mnt/sdc/V4R/WYH/Pytracking/github_ICRA26/data/vid_lmdb'
        self.imagenetdet_dir = ''
        self.ecssd_dir = ''
        self.hkuis_dir = ''
        self.msra10k_dir = ''
        self.davis_dir = ''
        self.youtubevos_dir = ''
        self.bdd100k_night_dir = '/mnt/sdc/V4R/WYH/Pytracking/github_ICRA26/data/bdd100k_night'
        self.exdark_dir = '/mnt/sdc/V4R/WYH/Pytracking/github_ICRA26/data/ExDark'
        self.shift_night_dir = '/mnt/sdc/V4R/WYH/Pytracking/github_ICRA26/data/shift_night'
